plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - COPYRIGHT.md

title: Dialogues with a Machine
description: Choose "Dialogues with a Machine" if it’s a narrative-driven work about a specific
  but relatable machine, emphasizing personal or grounded dialogues.
